#!/usr/bin/env bash
# Exercises the daemon's privileged paths on the machine it is running on.
#
# Compiling proves the code is syntactically valid. It does not prove the kernel accepts the
# ruleset, that a drop rule actually drops, or that removing it actually restores traffic -
# and those are the things whose failure mode is "the user's internet is gone and nothing says
# why". So they are checked here, for real, rather than claimed.
#
# Usage:  Tools/daemon-smoke.sh --nft | --tc | --block | --unblock | --macos-capability | --macos-dns
set -uo pipefail

MODE="${1:-}"
OUT="daemon-smoke"
API="http://localhost:8787/api/v1"
STATE="${XDG_STATE_HOME:-$HOME/.local/state}/netpilot/netpilot"

say() { printf '%s\n' "$1"; }
result() { printf '%s=%s\n' "$1" "$2"; }

# uid nobody owns on every Linux image; blocking it is a safe way to prove the rule works.
TEST_UID=65534

wait_for_api() {
  for _ in $(seq 1 40); do
    curl -sf "$API/ping" >/dev/null 2>&1 && return 0
    sleep 0.5
  done
  return 1
}

case "$MODE" in

--nft)
  # Feed the daemon's own generator to nft and see whether the kernel accepts it. The ruleset
  # is generated by running the daemon for real, not by re-typing it here, so this tests the
  # code path rather than a copy of it.
  rm -rf "$STATE"
  ./out/netpilotd > "$OUT.log" 2>&1 &
  DAEMON=$!
  if ! wait_for_api; then say "daemon did not start"; cat "$OUT.log"; kill $DAEMON 2>/dev/null; exit 1; fi

  curl -sf -X POST "$API/block" -H 'Content-Type: application/json' \
       -d "{\"uid\":$TEST_UID,\"blocked\":true}" > "$OUT-block.json"
  sleep 1
  kill $DAEMON 2>/dev/null; wait $DAEMON 2>/dev/null

  cat "$OUT-block.json"; say ""
  if nft list table inet netpilot >/dev/null 2>&1; then
    say "--- the chain the kernel has ---"
    nft list table inet netpilot
    result NFT_RULES_ACCEPTED yes
  else
    say "nft rejected or lost our table:"
    nft list table inet netpilot 2>&1 || true
    result NFT_RULES_ACCEPTED no
  fi
  ;;

--tc)
  rm -rf "$STATE"
  ./out/netpilotd > "$OUT.log" 2>&1 &
  DAEMON=$!
  if ! wait_for_api; then say "daemon did not start"; cat "$OUT.log"; kill $DAEMON 2>/dev/null; exit 1; fi

  DEV=$(ip -4 route show default | awk '{for(i=1;i<=NF;i++) if($i=="dev") print $(i+1)}' | head -1)
  say "uplink: ${DEV:-<none>}"
  curl -sf -X POST "$API/limit" -H 'Content-Type: application/json' \
       -d "{\"uid\":$TEST_UID,\"upBps\":131072}" > "$OUT-limit.json"
  sleep 1
  kill $DAEMON 2>/dev/null; wait $DAEMON 2>/dev/null

  cat "$OUT-limit.json"; say ""
  if [ -n "${DEV:-}" ] && tc qdisc show dev "$DEV" 2>/dev/null | grep -q htb; then
    say "--- qdisc on $DEV ---"
    tc qdisc show dev "$DEV"
    say "--- classes ---"
    tc class show dev "$DEV"
    result TC_COMMANDS_ACCEPTED yes
  else
    say "tc did not install the htb qdisc on ${DEV:-<none>}"
    result TC_COMMANDS_ACCEPTED no
  fi
  # Leave the interface as we found it, whatever happened above.
  [ -n "${DEV:-}" ] && tc qdisc del dev "$DEV" root 2>/dev/null
  ;;

--block)
  rm -rf "$STATE"
  ./out/netpilotd > "$OUT.log" 2>&1 &
  DAEMON=$!
  if ! wait_for_api; then say "daemon did not start"; cat "$OUT.log"; kill $DAEMON 2>/dev/null; exit 1; fi
  curl -sf -X POST "$API/block" -H 'Content-Type: application/json' \
       -d "{\"uid\":$TEST_UID,\"blocked\":true}" >/dev/null
  sleep 1
  kill $DAEMON 2>/dev/null; wait $DAEMON 2>/dev/null

  if nft list chain inet netpilot guard 2>/dev/null | grep -q "skuid $TEST_UID"; then
    result BLOCK_RULE_PRESENT yes
  else
    result BLOCK_RULE_PRESENT no
  fi

  # Does the rule actually drop? Measured, not assumed: a rule that exists but does not
  # match is exactly the failure that would leave someone believing an app is blocked.
  if command -v setpriv >/dev/null 2>&1; then
    if timeout 12 setpriv --reuid=$TEST_UID --regid=$TEST_UID --clear-groups \
         curl -s --max-time 8 -o /dev/null https://1.1.1.1 2>/dev/null; then
      result BLOCK_IS_EFFECTIVE no
    else
      result BLOCK_IS_EFFECTIVE yes
    fi
    # And confirm it is the rule, not a dead network: the same request as root must work.
    if timeout 12 curl -s --max-time 8 -o /dev/null https://1.1.1.1 2>/dev/null; then
      say "root can still reach the network, so the drop is specific to the blocked uid"
    else
      say "WARNING: root also cannot reach the network - this machine has no egress, so the"
      say "block test is inconclusive rather than a pass."
      result BLOCK_IS_EFFECTIVE unknown
    fi
  else
    say "setpriv is unavailable; cannot measure whether the block takes effect"
    result BLOCK_IS_EFFECTIVE unknown
  fi
  ;;

--unblock)
  rm -rf "$STATE"
  ./out/netpilotd > "$OUT.log" 2>&1 &
  DAEMON=$!
  if ! wait_for_api; then say "daemon did not start"; kill $DAEMON 2>/dev/null; exit 1; fi
  curl -sf -X POST "$API/block" -H 'Content-Type: application/json' \
       -d "{\"uid\":$TEST_UID,\"blocked\":true}" >/dev/null
  sleep 1
  curl -sf -X POST "$API/block" -H 'Content-Type: application/json' \
       -d "{\"uid\":$TEST_UID,\"blocked\":false}" >/dev/null
  sleep 1
  kill $DAEMON 2>/dev/null; wait $DAEMON 2>/dev/null

  if nft list chain inet netpilot guard 2>/dev/null | grep -q "skuid $TEST_UID"; then
    say "the rule is still present after unblock"
    result BLOCK_IS_EFFECTIVE yes
  else
    result BLOCK_IS_EFFECTIVE no
  fi
  if command -v setpriv >/dev/null 2>&1; then
    if timeout 12 setpriv --reuid=$TEST_UID --regid=$TEST_UID --clear-groups \
         curl -s --max-time 8 -o /dev/null https://1.1.1.1 2>/dev/null; then
      say "the unblocked uid can reach the network again"
    else
      say "NOTE: still unreachable - check whether this machine has egress at all"
    fi
  fi
  nft flush table inet netpilot 2>/dev/null
  ;;

--macos-capability)
  ./out/netpilotd > "$OUT.log" 2>&1 &
  DAEMON=$!
  if ! wait_for_api; then say "daemon did not start"; cat "$OUT.log"; kill $DAEMON 2>/dev/null; exit 1; fi
  curl -sf -X POST "$API/capability" -H 'Content-Type: application/json' \
       -d '{"uid":501}' > "$OUT-cap.json"
  kill $DAEMON 2>/dev/null; wait $DAEMON 2>/dev/null

  cat "$OUT-cap.json"; say ""
  SUPPORT=$(python3 -c "import json;print(json.load(open('$OUT-cap.json'))['support'])" 2>/dev/null)
  [ "$SUPPORT" = "None" ] && result MACOS_CAPABILITY none || result MACOS_CAPABILITY "$SUPPORT"

  # The refusal has to name the reason. A capability of "None" with an empty explanation is
  # no better than a switch that does nothing.
  if python3 - "$OUT-cap.json" <<'PY'
import json,sys
d=json.load(open(sys.argv[1]))
detail=(d.get("blockingProbe") or {}).get("Detail","")
sys.exit(0 if "Network Extension" in detail or "pf" in detail else 1)
PY
  then result MACOS_REFUSES_WITH_REASON yes
  else
    say "the refusal did not explain why:"
    cat "$OUT-cap.json"
    result MACOS_REFUSES_WITH_REASON no
  fi
  ;;

--macos-dns)
  if ! networksetup -listallnetworkservices >/dev/null 2>&1; then
    say "networksetup is unavailable on this Mac"
    result MACOS_DNS_READABLE no
    exit 1
  fi
  # Read every service the way the backend does. On CI the first service is a placeholder
  # that is disabled, so this proves the command runs, not that a real service was changed.
  networksetup -listallnetworkservices | tail -n +2 | while read -r svc; do
    case "$svc" in ""|"*"*) continue ;; esac
    say "  $svc"
    networksetup -getdnsservers "$svc" 2>&1 | sed 's/^/    /'
  done
  result MACOS_DNS_READABLE yes
  ;;

*)
  say "usage: $0 --nft | --tc | --block | --unblock | --macos-capability | --macos-dns"
  exit 2
  ;;
esac

# Always leave no trace: these tests change the firewall of the machine they run on.
nft flush table inet netpilot 2>/dev/null
exit 0